### ISSUE TITLE
Revise text file format to simple-text

### ISSUE THREAD

**Issue by jeffmurphy** [jeffmurphy/cse542#29]
Revise our format so that JSON is not used but instead a very simple custom format is used. 

In particular, according to Matt escape characters should never be needed. So this is acceptable:

question: What does "angular" mean?

but this is not acceptable:

question: "What does \"angular\" mean?

**Comment by jeffmurphy** [comment]
It's important to get this done quickly so that we can make progress on #30

**Comment by jeffmurphy** [comment]
See branch https://github.com/jeffmurphy/cse542/commits/issue-29

**Comment by jeffmurphy** [comment]
See branch https://github.com/jeffmurphy/cse542/commits/issue-29

**Comment by dvgokhale** [comment]
Just a bit busy today, will get back to you on this tomorrow. Is that ok?

Deepak

**Comment by jeffmurphy** [comment]
no worries. i'm going to work on it a bit on the project tonight.
