### ISSUE TITLE
Identify web-based platform and implement prototype

### ISSUE THREAD

**Issue by jeffmurphy** [jeffmurphy/cse542#30]
Prototype should be able to:

- read from a local folder and list out filenames contained in that folder
- user selects a filename
- file is parsed (see #29 regarding file format)
- based on parsed file, the UI renders the title, images, and assumptions, allows user to pick and assumption.

Once we get to that point, the rest is easy and we can divide up the work.

**Comment by ShivamGupta7795** [comment]
you can remove sgupta33 account. I'll be using another account from now on.
